#!/bin/bash
docker rm -v $(docker ps -a -q -f status=exited)
docker rmi $(docker images -f "dangling=true" -q)
docker volume rm $(docker volume ls -qf dangling=true)
cat <<EOF

  I HOPE YOU DIDN'T JUST PIPE THAT STRAIGHT TO SHELL

  GUI THAT IS NOT A SAFE THING TO DO WITH YOUR COMPUTER

EOF

